### ISSUE TITLE
Apk runtime error after repackaging

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#129]
The repackaged apk produced by debugging phase throws exception after login.

**Comment by MarcMil** [comment]
One issue was due to false handling of the transient modifier, which is fixed by now. Thus you need to download the newest build and reimport the apk.
However, this app expects a JSON formatted response, but gets HTML instead, which may lead to another crash.
I need to look deeper into this in order to say more.

**Comment by MarcMil** [comment]
I fixed another issue regarding the annotation handling. Also for this fix you need to reimport the APK using the newest CodeInspect version.

**Comment by StevenArzt** [comment]
@flankerhqd Can you confirm that the issue is resolved in the current version?

**Comment by flankerhqd** [comment]
I'll check, sorry for not for noticing the status in time.

**Comment by flankerhqd** [comment]
I checked the newest version of shopify, downloaded at http://storage.evozi.com/apk/dl/15/02/26/com.shopify.mobile.apk?h=ZicNZVT065sbG0--EzvVZw&t=1436093251, it enters ANR state after "Get Started", seems still not fixed

**Comment by MarcMil** [comment]
Yes. This is due to the soot bug I mentioned in your new bug report. Thanks for reporting; it seems that CodeInspect is currently broken due to soot. We are always using the newest nightly build of soot for CodeInspect, therefore you will encounter this behaviour for many apps, which contain long methods.

I hope you have an older version of CodeInspect around, if not, I can look on the build server which archived some of the more recent versions, from which the oldest should hopefully not yet contain this bug.

**Comment by flankerhqd** [comment]
Seems fixed in newest version.
